server:
  port: 9009
logging:
  level:
    com.javaboy.common.mapper: debug  #dao的路径
  config: src\main\resources\logback.xml #配不配效果好像都一样.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vul_table?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: